# There is the cert-bot initial commit.

diff --git a/buildew b/buildew
--- a/buildew
+++ b/buildew
@@ -70,6 +70,11 @@ DJANGO_SECRET_KEY=
 SERVICE_HTTP_HOST=localhost
 SERVICE_HTTP_PORT=8000
 HTTP_PORT=80
+
+HOST_HOSTNAME=localhost
+SERVER_PORT=443
+SERVER_SSL=ssl
+PUBLIC_DOMAIN=host.name
 EOF
 fi
 
@@ -78,7 +83,7 @@ echo "=========== $COMMAND"
 echo "$COMMAND ==========="
 echo COMMAND
 
-SERVICES=('postgresdb' 'service' 'front')
+SERVICES=('postgresdb' 'service' 'front' 'certbot')
 
 if [ "$COMMAND" == "redeps" ]; then
     echo "Reinstall dependencies"
@@ -129,6 +134,10 @@ function build {
 
     SERVICE_IMAGE_NAME=usalko/$SERVICE:front${DOCKER_TAG_SUFFIX}
     docker_build "$SERVICE_IMAGE_NAME" 'Dockerfile' '.' || exit 1
+
+    SERVICE_IMAGE_NAME=usalko/certbot
+    docker_build "$SERVICE_IMAGE_NAME" 'Dockerfile.certbot' '.' || exit 1
+
 }
 
 if [ "$COMMAND" == "build" ]; then
@@ -191,11 +200,9 @@ function start {
     # Check the data folders
     check_folder .data
     # Tune images folder
-    # mkdir -p .data/front/images || exit 1
-    # chmod a+rwx .data/front/images
-    # Tune static folder
-    # mkdir -p .data/front/admin/static || exit 1
-    # chmod a+rwx .data/front/admin/static
+    touch .data/certbot/regru.ini
+    mkdir .data/certbot/wwww
+    mkdir .data/certbot/conf
 
     # Sync Images, TODO: put on s3 storage
     # cp back/app/static/images/photo_2021-11-10_11-15-00.jpg .data/front/images/cover
@@ -250,26 +257,32 @@ if [ "$COMMAND" == "publish" ]; then
     echo 'Publish docker images to dockerhub'
 
     build || {
-        echo "Line 243: Error in build... Exit..."
+        echo "Line 262: Error in build... Exit..."
         exit 1
     }
 
     IMAGE=usalko/test4:v1${DOCKER_TAG_SUFFIX}
     docker push "$IMAGE" || {
-        echo "Line 248: Error in push to dockerhub image $IMAGE ... Exit..."
+        echo "Line 268: Error in push to dockerhub image $IMAGE ... Exit..."
         exit 1
     }
 
     IMAGE=usalko/test4:front${DOCKER_TAG_SUFFIX}
     docker push "$IMAGE" || {
-        echo "Line 252: Error in push to dockerhub image $IMAGE... Exit..."
+        echo "Line 274: Error in push to dockerhub image $IMAGE... Exit..."
+        exit 1
+    }
+
+    IMAGE=usalko/certbot
+    docker push "$IMAGE" || {
+        echo "Line 281: Error in push to dockerhub image $IMAGE... Exit..."
         exit 1
     }
 
 fi
 
 function remove_front_image {
-    FRONT_CONTAINER=$(docker image ls | grep front | awk '{ print $3 }')
+    FRONT_CONTAINER=$(docker image ls | grep front | awk 'NR==1{ print $3 }')
     docker image rm "$FRONT_CONTAINER" --force
 }
 
@@ -322,8 +335,41 @@ if [ "$COMMAND" == "logs" ]; then
     fi
 fi
 
+# ================================= CERTBOT =======================================================
+if [ "$COMMAND" == "certbot-test-run" ]; then
+    [ -n "$1" ] || [ "$1" == "*" ] || {
+        echo "Please determine the host name for the domain $PUBLIC_DOMAIN, as an example for my-host.$PUBLIC_DOMAIN: ./buildew certbot-test-run my-host"
+        exit 63
+    }
+    if [ "$1" == "*" ]; then
+        echo "Test run (dry run) certbot for the host: *.$PUBLIC_DOMAIN"
+        docker compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d "$PUBLIC_DOMAIN"
+    else
+        echo "Test run (dry run) certbot for the host: $1.$PUBLIC_DOMAIN"
+        docker compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d "$1.$PUBLIC_DOMAIN"
+    fi
+fi
+
+if [ "$COMMAND" == "certbot-run" ]; then
+    [ -n "$1" ] || [ "$1" == "*" ] || {
+        echo "Please determine the host name for the domain $PUBLIC_DOMAIN, as an example for my-host.$PUBLIC_DOMAIN: ./buildew certbot-run my-host"
+        exit 77
+    }
+    if [ "$1" == "*" ]; then
+        echo "Test run (dry run) certbot for the host: *.$PUBLIC_DOMAIN"
+        docker compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ -d "$PUBLIC_DOMAIN"
+    else
+        echo "Run certbot for the host: $1.$PUBLIC_DOMAIN"
+        docker compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ -d "$1.$PUBLIC_DOMAIN"
+    fi
+fi
+
+if [ "$COMMAND" == "certbot-renew" ]; then
+    docker compose run --rm certbot renew
+fi
+
 # =================================================================================================
 
-AVAILABLE_COMMANDS="run build up start stop down finish restart manage service redeps renew renew-front renew-back clean log logs publish"
+AVAILABLE_COMMANDS="run build up start stop down finish restart manage service redeps renew renew-front renew-back clean log logs publish certbot-test-run certbot-run certbot-renew"
 echo ''
 [[ $AVAILABLE_COMMANDS =~ (^| )$COMMAND($| ) ]] && echo 'Ok' || echo 'Unknown command: ' "$COMMAND" && echo 'Available commands are: ' "$AVAILABLE_COMMANDS"
